// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmV6YQcEW91rZ7vTRQJ1v41R2N3_gXxY8',
    appId: '1:50067802319:web:43f4c23ae7b2ac18294fba',
    messagingSenderId: '50067802319',
    projectId: 'limpexia-86c92',
    authDomain: 'limpexia-86c92.firebaseapp.com',
    databaseURL: 'https://limpexia-86c92-default-rtdb.firebaseio.com',
    storageBucket: 'limpexia-86c92.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_WJdp04Lo3l3zcFO31n6no1QL-oN6J50',
    appId: '1:50067802319:android:4b845554e04e4e11294fba',
    messagingSenderId: '50067802319',
    projectId: 'limpexia-86c92',
    databaseURL: 'https://limpexia-86c92-default-rtdb.firebaseio.com',
    storageBucket: 'limpexia-86c92.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDtre6LA4NmVLxR8k_lRy_gruVXExwBD6M',
    appId: '1:50067802319:ios:b7bfe1cd460bcb1b294fba',
    messagingSenderId: '50067802319',
    projectId: 'limpexia-86c92',
    databaseURL: 'https://limpexia-86c92-default-rtdb.firebaseio.com',
    storageBucket: 'limpexia-86c92.firebasestorage.app',
    iosBundleId: 'com.example.limpexiaExpressApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDtre6LA4NmVLxR8k_lRy_gruVXExwBD6M',
    appId: '1:50067802319:ios:b7bfe1cd460bcb1b294fba',
    messagingSenderId: '50067802319',
    projectId: 'limpexia-86c92',
    databaseURL: 'https://limpexia-86c92-default-rtdb.firebaseio.com',
    storageBucket: 'limpexia-86c92.firebasestorage.app',
    iosBundleId: 'com.example.limpexiaExpressApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmV6YQcEW91rZ7vTRQJ1v41R2N3_gXxY8',
    appId: '1:50067802319:web:7e74abc708c91aac294fba',
    messagingSenderId: '50067802319',
    projectId: 'limpexia-86c92',
    authDomain: 'limpexia-86c92.firebaseapp.com',
    databaseURL: 'https://limpexia-86c92-default-rtdb.firebaseio.com',
    storageBucket: 'limpexia-86c92.firebasestorage.app',
  );

}