// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9Q5FHGP6GzASXeF_AtwsqbJoK54JKogk',
    appId: '1:460133570608:web:2f92352e4cff3e4b5035f5',
    messagingSenderId: '460133570608',
    projectId: 'limpexia-1c584',
    authDomain: 'limpexia-1c584.firebaseapp.com',
    databaseURL: 'https://limpexia-1c584-default-rtdb.firebaseio.com',
    storageBucket: 'limpexia-1c584.firebasestorage.app',
    measurementId: 'G-YRX91NKXPT',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKSa9stYqkGuFJE8zV3BTbpHSvn8TZBgI',
    appId: '1:460133570608:android:3452f496cc31e70b5035f5',
    messagingSenderId: '460133570608',
    projectId: 'limpexia-1c584',
    databaseURL: 'https://limpexia-1c584-default-rtdb.firebaseio.com',
    storageBucket: 'limpexia-1c584.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCj0zQm1jijE4qkTz7R_WCYP0X56Y0Do5I',
    appId: '1:460133570608:ios:6dc95a1e449480655035f5',
    messagingSenderId: '460133570608',
    projectId: 'limpexia-1c584',
    databaseURL: 'https://limpexia-1c584-default-rtdb.firebaseio.com',
    storageBucket: 'limpexia-1c584.firebasestorage.app',
    iosBundleId: 'com.example.limpexiaExpressApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCj0zQm1jijE4qkTz7R_WCYP0X56Y0Do5I',
    appId: '1:460133570608:ios:6dc95a1e449480655035f5',
    messagingSenderId: '460133570608',
    projectId: 'limpexia-1c584',
    databaseURL: 'https://limpexia-1c584-default-rtdb.firebaseio.com',
    storageBucket: 'limpexia-1c584.firebasestorage.app',
    iosBundleId: 'com.example.limpexiaExpressApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9Q5FHGP6GzASXeF_AtwsqbJoK54JKogk',
    appId: '1:460133570608:web:a5956287f31fb4b35035f5',
    messagingSenderId: '460133570608',
    projectId: 'limpexia-1c584',
    authDomain: 'limpexia-1c584.firebaseapp.com',
    databaseURL: 'https://limpexia-1c584-default-rtdb.firebaseio.com',
    storageBucket: 'limpexia-1c584.firebasestorage.app',
    measurementId: 'G-DBRTKYZP3B',
  );
}
